# Generated by Django 4.2.5 on 2023-10-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t4app', '0004_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
