server:
  port: 8090


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: myApp
          uri: http://localhost:8082/
          predicates:
            - Path=/myapp/**
